server:
  port: 8090

spring:
  datasource:
    url: jdbc:sqlserver://springboot-server.database.windows.net:1433;database=curd;user=admin@123@springboot-server;password=pass@word1;encrypt=true;trustServerCertificate=false;loginTimeout=30
#    username: admin@123@springboot-server
#    password: pass@word1

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true

